import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import { Calendar } from './components/Calendar'
import { Leaderboard } from './components/Leaderboard'
import { UserLookup } from './components/UserLookup'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Calendar start={new Date(1647388800000)} end={new Date()} />
        <Leaderboard />
        <UserLookup />
      </main>
    </div>
  )
}

export default Home
